### ISSUE TITLE
Please provide a license

### ISSUE THREAD

**Issue by FlorianWilhelm** [andodet/git-overview#6]
Hi @andodet, awesome demo project! Could you provide also a license file or mention the license of this code somewhere? I would like to reuse parts of it if allowed which is always problematic if there is no license stated. Best would be MIT of course :-)

**Comment by andodet** [comment]
Hi @FlorianWilhelm, will definitely upload a `LICENSE` file ASAP. I'll definitely go for MIT, so feel free to do whatever you want with the repo in the meantime.

**Comment by FlorianWilhelm** [comment]
Cool, thanks for the quick and positive feedback @andodet!

**Comment by FlorianWilhelm** [comment]
Thanks @andodet!

**Comment by FlorianWilhelm** [comment]
Thanks, I used your code in a [streamlit-demo app](https://github.com/pyscaffold/streamlit-demo) to demonstrate how it is possible to structure a streamlit application with [PyScaffold](https://pyscaffold.org/). I hope this is fine for your.

**Comment by andodet** [comment]
Thanks a lot @FlorianWilhelm, I've never used `PyScaffold` but that looks definitely interesting.
